// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWPzh6lPHhzcuPLQBO_gecrYc0xNPn2K8',
    appId: '1:871731269072:web:c27739cc31263fcd2dfdd5',
    messagingSenderId: '871731269072',
    projectId: 'peepsterdb',
    authDomain: 'peepsterdb.firebaseapp.com',
    storageBucket: 'peepsterdb.firebasestorage.app',
    measurementId: 'G-3XRRP724JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzBb3qzanmZGtYgeK0AlXdxWEswswlpc',
    appId: '1:871731269072:android:6b89491397c7820e2dfdd5',
    messagingSenderId: '871731269072',
    projectId: 'peepsterdb',
    storageBucket: 'peepsterdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGyzoU1rJcs0ltxFC6wnkoAYKFEAREIxw',
    appId: '1:871731269072:ios:34a95aa62d7441382dfdd5',
    messagingSenderId: '871731269072',
    projectId: 'peepsterdb',
    storageBucket: 'peepsterdb.firebasestorage.app',
    iosBundleId: 'com.example.peepster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGyzoU1rJcs0ltxFC6wnkoAYKFEAREIxw',
    appId: '1:871731269072:ios:34a95aa62d7441382dfdd5',
    messagingSenderId: '871731269072',
    projectId: 'peepsterdb',
    storageBucket: 'peepsterdb.firebasestorage.app',
    iosBundleId: 'com.example.peepster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWPzh6lPHhzcuPLQBO_gecrYc0xNPn2K8',
    appId: '1:871731269072:web:015664a416a000232dfdd5',
    messagingSenderId: '871731269072',
    projectId: 'peepsterdb',
    authDomain: 'peepsterdb.firebaseapp.com',
    storageBucket: 'peepsterdb.firebasestorage.app',
    measurementId: 'G-DLHR044ME2',
  );
}
